drop table if exists permiso_rol;
drop table if exists permiso;
drop table if exists telefono;
drop table if exists documento;
drop table if exists tipo_documento;
drop table if exists rec_est;
drop table if exists reclamo;
drop table if exists tipo_reclamo;
drop table if exists auditoria;
drop table if exists usuario;
drop table if exists rol;
drop table if exists c_pre;
drop table if exists preferencia;
drop table if exists lista_deseo;
drop table if exists sistema_milla;
drop table if exists metodo_pago;
drop table if exists banco;
drop table if exists tipo_billetera_digital;
drop table if exists pago;
drop table if exists cambio_moneda;
drop table if exists reembolso;
drop table if exists ven_est;
drop table if exists cuo_ecuo;
drop table if exists estado;
drop table if exists cuota;
drop table if exists plan_cuotas;
drop table if exists terminal_operacion;
drop table if exists cupo;
drop table if exists transporte;
drop table if exists imagen;
drop table if exists descuento;
drop table if exists r_a;
drop table if exists ambiente;
drop table if exists r_tc;
drop table if exists tipo_comida;
drop table if exists restriccion;
drop table if exists itinerario;
drop table if exists resena;
drop table if exists paquete_servicio;
drop table if exists servicio;
drop table if exists proveedor;
drop table if exists lugar;
drop table if exists viaje;
drop table if exists alquiler_vehiculo;
drop table if exists hotel;
drop table if exists restaurante;
drop table if exists paquete;
drop table if exists pasajero;
drop table if exists cliente cascade;
drop table if exists venta CASCADE;
drop function if exists agregar_permisos_rol(integer, integer[]);
drop function if exists eliminar_permisos_rol(integer, integer[]);
drop function if exists obtener_rol_permisos(integer);
drop function if exists insertar_rol(integer, varchar, integer[]);
drop function if exists eliminar_rol(integer);
drop function if exists insertar_usuario(varchar, varchar, integer, integer, integer);
drop function if exists insertar_documento_cliente(integer, integer, integer, integer, date, date);
drop function if exists obtener_documento_cliente(integer);
drop function if exists eliminar_documento_cliente(integer, integer);
drop function if exists inicio_sesion(varchar, varchar);
drop function if exists listar_roles();
drop function if exists listar_permisos();
drop function if exists listar_usuarios();
drop function if exists listar_clientes_dropdown();
drop function if exists listar_proveedores_dropdown();
drop function if exists cambiar_estado_usuario(integer, integer);
drop function if exists eliminar_rol_seguro(integer);
drop function if exists actualizar_nombre_rol(integer, varchar);
drop function if exists insertar_servicio_viaje_aereolinea(varchar, varchar, integer, integer, varchar, integer, integer, integer, varchar, integer, varchar, integer, character varying[]);
drop function if exists obtener_servicio_viaje_aereolinea(integer);
drop function if exists alterar_servicio_viaje_aereolinea(integer, varchar, varchar, integer, integer, varchar, integer, integer, varchar, integer, varchar, integer, character varying[]);
drop function if exists eliminar_servicio_viaje_aereolinea(integer);
drop function if exists insertar_cliente(varchar, varchar, varchar, varchar, varchar, varchar, integer, bigint[], varchar, varchar, date);
drop function if exists insertar_paquete(integer, varchar, varchar, varchar, character varying[], integer[]);
drop function if exists obtener_paquete(integer);
drop function if exists alterar_paquete(integer, varchar, varchar, varchar, character varying[], integer[]);
drop function if exists eliminar_paquete(integer);
drop function if exists insertar_descuento(integer, numeric, date);
drop function if exists obtener_descuentos_servicio(integer);
drop function if exists alterar_descuento(integer, numeric, date);
drop function if exists eliminar_descuento(integer);
drop function if exists obtener_tasa_cambio_actual();
drop function if exists actualizar_estado_venta(integer, varchar);
drop function if exists iniciar_venta(integer);
drop function if exists eliminar_item_itinerario(integer);
drop function if exists obtener_itinerario_venta(integer);
drop function if exists obtener_pagos_venta(integer);
drop function if exists insertar_proveedor(varchar, varchar, varchar, bigint[], date, integer, varchar);
drop function if exists insertar_metodo_pago_cripto(integer, varchar, varchar);
drop function if exists obtener_metodos_pago_cliente(integer);
drop function if exists alterar_metodo_pago_tarjeta(integer, integer, integer, date, varchar, varchar, integer);
drop function if exists alterar_metodo_pago_cheque(integer, integer, integer, integer);
drop function if exists alterar_metodo_pago_deposito(integer, integer, integer, integer);
drop function if exists alterar_metodo_pago_billetera(integer, integer, integer, integer);
drop function if exists alterar_metodo_pago_cripto(integer, varchar, varchar);
drop function if exists eliminar_metodo_pago(integer);
drop function if exists rep_obtener_valor_tasa_cambio(varchar);
drop function if exists rep_obtener_valor_descuento(integer);
drop function if exists rep_top_destinos_vendidos();
drop function if exists rep_servicios_populares(date, date, integer);
drop function if exists rep_ventas_periodo(date, date);
drop function if exists rep_clientes_activos(date, date, integer);
drop function if exists rep_ingresos_metodos_pago(date, date);
drop function if exists recalcular_monto_venta(integer, integer, integer, varchar, numeric);
drop function if exists agregar_item_itinerario(integer, integer, date);
drop function if exists vender_paquete(integer, integer, timestamp without time zone[]);
drop function if exists agregar_pasajero(integer, varchar, varchar, integer, varchar, date, estado_civil_enum);
drop function if exists eliminar_pasajero(integer, varchar);
drop function if exists insertar_metodo_pago_tarjeta(integer, bigint, integer, date, varchar, varchar, integer);
drop function if exists insertar_metodo_pago_deposito(integer, bigint, bigint, integer);
drop function if exists insertar_metodo_pago_billetera(integer, bigint, integer, integer);
drop function if exists insertar_metodo_pago_cheque(integer, bigint, bigint, integer);
drop function if exists registrar_pago(integer, bigint, integer, varchar);
drop function if exists rep_proveedores_mas_vendidos(date, date, integer);
drop type if exists tipo_metodo_pago_enum;
drop type if exists estado_civil_enum;
drop type if exists tipo_proveedor_enum;